<?php

return [
    'title' => 'DALT Fullstack',
    'description' => 'Build one real application across React, TypeScript, DALT and PostgreSQL.',
    'parts' => [
        '00' => ['title' => 'Web foundations', 'purpose' => 'Understand documents, forms, and the browser/server exchange.', 'lessons' => ['20-fs00-1-browser-and-http', '54-fs00-2-html-documents-and-semantics', '55-fs00-3-native-forms-and-http', '21-fs00-2-forms-json-and-spa'], 'milestones' => [['id' => 'B00', 'title' => 'Trace the system', 'route' => '/learn/fullstack/build/b00', 'prerequisites' => ['20-fs00-1-browser-and-http', '54-fs00-2-html-documents-and-semantics', '55-fs00-3-native-forms-and-http', '21-fs00-2-forms-json-and-spa']]]],
        '01' => ['title' => 'Modern JavaScript', 'purpose' => 'Remove JavaScript friction before TypeScript and React.', 'lessons' => ['22-fs01-1-data-functions-transformations', '56-fs01-2-functions-arrays-and-transformations', '23-fs01-2-modules-async-and-failure', '57-fs01-4-promises-fetch-and-failure'], 'milestones' => [['id' => 'B01', 'title' => 'JavaScript readiness', 'route' => '/learn/fullstack/build/b01', 'prerequisites' => ['22-fs01-1-data-functions-transformations', '56-fs01-2-functions-arrays-and-transformations', '23-fs01-2-modules-async-and-failure', '57-fs01-4-promises-fetch-and-failure']]]],
        '02' => ['title' => 'TypeScript foundations', 'purpose' => 'Model application data with useful, explicit types.', 'lessons' => ['24-fs02-1-typescript-mental-model', '58-fs02-2-everyday-types-and-inference', '25-fs02-2-modeling-application-data', '26-fs02-3-unions-narrowing-and-unknown', '27-fs02-4-functions-generics-and-reusable-types', '28-fs02-5-runtime-boundaries'], 'milestones' => [['id' => 'B02', 'title' => 'Type the future application', 'route' => '/learn/fullstack/build/b02', 'prerequisites' => ['24-fs02-1-typescript-mental-model', '58-fs02-2-everyday-types-and-inference', '25-fs02-2-modeling-application-data', '26-fs02-3-unions-narrowing-and-unknown', '27-fs02-4-functions-generics-and-reusable-types', '28-fs02-5-runtime-boundaries']]]],
        '03' => ['title' => 'React foundations', 'purpose' => 'Build the first issue-tracker interface.', 'lessons' => ['29-fs03-1-components-jsx-and-typed-props', '59-fs03-2-props-and-composition', '60-fs03-3-lists-conditionals-and-keys', '30-fs03-2-state-and-events', '61-fs03-5-state-structure-and-ownership', '31-fs03-3-forms-and-state-design', '62-fs03-7-css-and-tailwind-v4', '32-fs03-4-tailwind-and-accessible-ui'], 'milestones' => [['id' => 'B03', 'title' => 'The local issue tracker', 'route' => '/learn/fullstack/build/b03', 'prerequisites' => ['29-fs03-1-components-jsx-and-typed-props', '59-fs03-2-props-and-composition', '60-fs03-3-lists-conditionals-and-keys', '30-fs03-2-state-and-events', '61-fs03-5-state-structure-and-ownership', '31-fs03-3-forms-and-state-design', '62-fs03-7-css-and-tailwind-v4', '32-fs03-4-tailwind-and-accessible-ui']]]],
        '04' => ['title' => 'React and server', 'purpose' => 'Connect the interface to a server deliberately.', 'lessons' => ['33-fs04-1-fetching-data-and-effects', '63-fs04-2-loading-failure-and-races', '34-fs04-2-mutating-server-data', '35-fs04-3-separating-transport-from-ui'], 'milestones' => [['id' => 'B04', 'title' => 'First full-stack loop', 'route' => '/learn/fullstack/build/b04', 'prerequisites' => ['33-fs04-1-fetching-data-and-effects', '63-fs04-2-loading-failure-and-races', '34-fs04-2-mutating-server-data', '35-fs04-3-separating-transport-from-ui']]]],
        '05' => ['title' => 'DALT API and PostgreSQL', 'purpose' => 'Make the application persistent and useful.', 'lessons' => ['36-fs05-1-designing-the-application-api', '37-fs05-2-relational-modeling-and-migrations', '38-fs05-3-crud-queries-and-transaction-boundaries'], 'milestones' => [['id' => 'B05', 'title' => 'Persistent application', 'route' => '/learn/fullstack/build/b05', 'prerequisites' => ['36-fs05-1-designing-the-application-api', '37-fs05-2-relational-modeling-and-migrations', '38-fs05-3-crud-queries-and-transaction-boundaries']]]],
        '06' => ['title' => 'Testing, users and authentication', 'purpose' => 'Protect a multi-user application with evidence.', 'lessons' => ['39-fs06-1-backend-api-behavior-tests', '40-fs06-2-users-passwords-sessions-and-csrf', '41-fs06-3-authorization-and-ownership'], 'milestones' => [['id' => 'B06', 'title' => 'Multi-user protected system', 'route' => '/learn/fullstack/build/b06', 'prerequisites' => ['39-fs06-1-backend-api-behavior-tests', '40-fs06-2-users-passwords-sessions-and-csrf', '41-fs06-3-authorization-and-ownership']]]],
        '07' => ['title' => 'React structure, routing and testing', 'purpose' => 'Make the frontend navigable and dependable.', 'lessons' => ['42-fs07-1-urls-and-react-router', '43-fs07-2-authentication-in-the-frontend', '44-fs07-3-test-frontend-behavior'], 'milestones' => [['id' => 'B07', 'title' => 'Navigable tested application', 'route' => '/learn/fullstack/build/b07', 'prerequisites' => ['42-fs07-1-urls-and-react-router', '43-fs07-2-authentication-in-the-frontend', '44-fs07-3-test-frontend-behavior']]]],
        '08' => ['title' => 'Server and application state', 'purpose' => 'Choose state boundaries on purpose.', 'lessons' => ['45-fs08-1-client-state-versus-server-state', '46-fs08-2-mutations-invalidation-and-optimistic-ui', '47-fs08-3-context-reducers-and-zustand'], 'milestones' => [['id' => 'B08', 'title' => 'Intentional state architecture', 'route' => '/learn/fullstack/build/b08', 'prerequisites' => ['45-fs08-1-client-state-versus-server-state', '46-fs08-2-mutations-invalidation-and-optimistic-ui', '47-fs08-3-context-reducers-and-zustand']]]],
        '09' => ['title' => 'Advanced React and tooling', 'purpose' => 'Keep a growing frontend maintainable.', 'lessons' => ['48-fs09-1-custom-hooks-and-feature-boundaries', '49-fs09-2-build-pipeline-configuration-and-failure-boundaries'], 'milestones' => [['id' => 'B09', 'title' => 'Maintainable frontend', 'route' => '/learn/fullstack/build/b09', 'prerequisites' => ['48-fs09-1-custom-hooks-and-feature-boundaries', '49-fs09-2-build-pipeline-configuration-and-failure-boundaries']]]],
        '10' => ['title' => 'Docker', 'purpose' => 'Run the whole system in a real environment.', 'lessons' => ['50-fs10-1-containers-around-the-application', '51-fs10-2-builds-health-and-debugging'], 'milestones' => [['id' => 'B10', 'title' => 'Containerized full stack', 'route' => '/learn/fullstack/build/b10', 'prerequisites' => ['50-fs10-1-containers-around-the-application', '51-fs10-2-builds-health-and-debugging']]]],
        '11' => ['title' => 'PostgreSQL deeper', 'purpose' => 'Make database-aware product decisions.', 'lessons' => ['52-fs11-1-query-performance-and-postgresql-capabilities', '53-fs11-2-transactions-concurrency-and-row-isolation'], 'milestones' => [['id' => 'B11', 'title' => 'Database-aware application', 'route' => '/learn/fullstack/build/b11', 'prerequisites' => ['52-fs11-1-query-performance-and-postgresql-capabilities', '53-fs11-2-transactions-concurrency-and-row-isolation']]]],
        '12' => ['title' => 'Capstone', 'purpose' => 'Audit, explain, and freeze the finished system.', 'lessons' => [], 'milestones' => [
            ['id' => 'C01', 'title' => 'System audit', 'route' => '/learn/fullstack/build/c01', 'prerequisites' => ['53-fs11-2-transactions-concurrency-and-row-isolation']],
            ['id' => 'C02', 'title' => 'Complete one workflow', 'route' => '/learn/fullstack/build/c02', 'prerequisites' => ['53-fs11-2-transactions-concurrency-and-row-isolation']],
            ['id' => 'C03', 'title' => 'Failure-path hardening', 'route' => '/learn/fullstack/build/c03', 'prerequisites' => ['53-fs11-2-transactions-concurrency-and-row-isolation']],
            ['id' => 'C04', 'title' => 'Test hardening', 'route' => '/learn/fullstack/build/c04', 'prerequisites' => ['53-fs11-2-transactions-concurrency-and-row-isolation']],
            ['id' => 'C05', 'title' => 'Performance review', 'route' => '/learn/fullstack/build/c05', 'prerequisites' => ['53-fs11-2-transactions-concurrency-and-row-isolation']],
            ['id' => 'C06', 'title' => 'Laravel comparison', 'route' => '/learn/fullstack/build/c06', 'prerequisites' => ['53-fs11-2-transactions-concurrency-and-row-isolation']],
            ['id' => 'C07', 'title' => 'Explain and freeze', 'route' => '/learn/fullstack/build/c07', 'prerequisites' => ['53-fs11-2-transactions-concurrency-and-row-isolation']],
        ]],
    ],
];
